export const APPEAL_REQUEST = "APPEAL_REQUEST";

export const APPEAL_SUCCESS = "APPEAL_SUCCESS";
export const APPEAL_FAIL = "APPEAL_FAIL";

export const APPEAL_UPDATAE_SUCCESS = "APPEAL_UPDATE_SUCCESS";
export const APPEAL_UPDATE_FAIL = "APPEAL_UPDATE_FAIL";

export const APPEAL_DELETE_SUCCESS = "APPEAL_DELETE_SUCCESS";
export const APPEAL_DELETE_FAIL = "APPEAL_DELETE_FAIL";

export const APPEAL_LIST_SUCCESS = "APPEAL_LIST_SUCCESS";
export const APPEAL_LIST_FAIL = "APPEAL_LIST_FAIL";

export const APPEAL_BY_ID_SUCCESS = "APPEAL_BY_ID_SUCCESS";
export const APPEAL_BY_ID_FAIL = "APPEAL_BY_ID_FAIL";

export const APPEAL_MEDIA_SUCCESS = "APPEAL_MEDIA_SUCCESS";
export const APPEAL_MEDIA_FAIL = "APPEAL_MEDIA_FAIL";

export const APPEAL_MEDIA_DELETE_SUCCESS = "APPEAL_MEDIA_DELETE_SUCCESS";
export const APPEAL_MEDIA_DELETE_FAIL = "APPEAL_MEDIA_DELETE_FAIL";

export const APPEAL_PARAGRAPH_SUCCESS = "APPEAL_PARAGRAPH_SUCCESS";
export const APPEAL_PARAGRAPH_FAIL = "APPEAL_PARAGRAPH_FAIL";

export const APPEAL_PARAGRAPH_UPDATE_SUCCESS = "APPEAL_PARAGRAPH_UPDATE_SUCCESS";
export const APPEAL_PARAGRAPH_UPDATE_FAIL = "APPEAL_PARAGRAPH_UPDATE_FAIL";

export const APPEAL_PARAGRAPH_DELETE_SUCCESS = "APPEAL_PARAGRAPH_DELETE_SUCCESS";
export const APPEAL_PARAGRAPH_DELETE_FAIL = "APPEAL_PARAGRAPH_DELETE_FAIL";

export const APPEAL_PARAGRAPH_BY_ID_SUCCESS = "APPEAL_PARAGRAPH_BY_ID_SUCCESS";
export const APPEAL_PARAGRAPH_BY_ID_FAIL = "APPEAL_PARAGRAPH_BY_ID_FAIL";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
