export const CAMPAIGN_REQUEST = "CAMPAIGN_REQUEST";

export const CAMPAIGN_SUCCESS = "CAMPAIGN_SUCCESS";
export const CAMPAIGN_FAIL = "CAMPAIGN_FAIL";

export const CAMPAIGN_UPDATAE_SUCCESS = "CAMPAIGN_UPDATE_SUCCESS";
export const CAMPAIGN_UPDATE_FAIL = "CAMPAIGN_UPDATE_FAIL";

export const CAMPAIGN_DELETE_SUCCESS = "CAMPAIGN_DELETE_SUCCESS";
export const CAMPAIGN_DELETE_FAIL = "CAMPAIGN_DELETE_FAIL";

export const CAMPAIGN_LIST_SUCCESS = "CAMPAIGN_LIST_SUCCESS";
export const CAMPAIGN_LIST_FAIL = "CAMPAIGN_LIST_FAIL";

export const CAMPAIGN_BY_ID_SUCCESS = "CAMPAIGN_BY_ID_SUCCESS";
export const CAMPAIGN_BY_ID_FAIL = "CAMPAIGN_BY_ID_FAIL";

export const CAMPAIGN_MEDIA_SUCCESS = "CAMPAIGN_MEDIA_SUCCESS";
export const CAMPAIGN_MEDIA_FAIL = "CAMPAIGN_MEDIA_FAIL";

export const CAMPAIGN_MEDIA_DELETE_SUCCESS = "CAMPAIGN_MEDIA_DELETE_SUCCESS";
export const CAMPAIGN_MEDIA_DELETE_FAIL = "CAMPAIGN_MEDIA_DELETE_FAIL";

export const CAMPAIGN_PARAGRAPH_SUCCESS = "CAMPAIGN_PARAGRAPH_SUCCESS";
export const CAMPAIGN_PARAGRAPH_FAIL = "CAMPAIGN_PARAGRAPH_FAIL";

export const CAMPAIGN_PARAGRAPH_UPDATE_SUCCESS = "CAMPAIGN_PARAGRAPH_UPDATE_SUCCESS";
export const CAMPAIGN_PARAGRAPH_UPDATE_FAIL = "CAMPAIGN_PARAGRAPH_UPDATE_FAIL";

export const CAMPAIGN_PARAGRAPH_DELETE_SUCCESS = "CAMPAIGN_PARAGRAPH_DELETE_SUCCESS";
export const CAMPAIGN_PARAGRAPH_DELETE_FAIL = "CAMPAIGN_PARAGRAPH_DELETE_FAIL";

export const CAMPAIGN_PARAGRAPH_BY_ID_SUCCESS = "CAMPAIGN_PARAGRAPH_BY_ID_SUCCESS";
export const CAMPAIGN_PARAGRAPH_BY_ID_FAIL = "CAMPAIGN_PARAGRAPH_BY_ID_FAIL";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
