export const DONATION_REQUEST = "DONATION_REQUEST";

export const DONATION_SUCCESS = "DONATION_SUCCESS";
export const DONATION_FAIL = "DONATION_FAIL";

export const DONATION_LIST_SUCCESS = "DONATION_LIST_SUCCESS";
export const DONATION_LIST_FAIL = "DONATION_LIST_FAIL";

export const DONATION_BY_ID_SUCCESS = "DONATION_BY_ID_SUCCESS";
export const DONATION_BY_ID_FAIL = "DONATION_BY_ID_FAIL";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
