export const FORGOTPASSWORD_REQUEST = "FORGOTPASSWORD_REQUEST";

export const FORGOTPASSWORD_SUCCESS = "FORGOTPASSWORD_SUCCESS";
export const FORGOTPASSWORD_FAIL = "FORGOTPASSWORD_FAIL";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
