export const IMAGEGALLERY_REQUEST = "IMAGEGALLERY_REQUEST";

export const IMAGEGALLERY_SUCCESS = "IMAGEGALLERY_SUCCESS";
export const IMAGEGALLERY_FAIL = "IMAGEGALLERY_FAIL";
export const IMAGEGALLERY_LIST_SUCCESS = "IMAGEGALLERY_LIST_SUCCESS";
export const IMAGEGALLERY_LIST_FAIL = "IMAGEGALLERY_LIST_FAIL";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";