export const MESSAGE_REQUEST = "MESSAGE_REQUEST";

export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_FAIL = "MESSAGE_FAIL";

export const MESSAGE_UPDATAE_SUCCESS = "MESSAGE_UPDATE_SUCCESS";
export const MESSAGE_UPDATE_FAIL = "MESSAGE_UPDATE_FAIL";

export const MESSAGE_DELETE_SUCCESS = "MESSAGE_DELETE_SUCCESS";
export const MESSAGE_DELETE_FAIL = "MESSAGE_DELETE_FAIL";

export const MESSAGE_LIST_SUCCESS = "MESSAGE_LIST_SUCCESS";
export const MESSAGE_LIST_FAIL = "MESSAGE_LIST_FAIL";

export const MESSAGE_BY_ID_SUCCESS = "MESSAGE_BY_ID_SUCCESS";
export const MESSAGE_BY_ID_FAIL = "MESSAGE_BY_ID_FAIL";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
