export const NEWS_REQUEST = "NEWS_REQUEST";

export const NEWS_SUCCESS = "NEWS_SUCCESS";
export const NEWS_FAIL = "NEWS_FAIL";

export const NEWS_UPDATAE_SUCCESS = "NEWS_UPDATE_SUCCESS";
export const NEWS_UPDATE_FAIL = "NEWS_UPDATE_FAIL";

export const NEWS_DELETE_SUCCESS = "NEWS_DELETE_SUCCESS";
export const NEWS_DELETE_FAIL = "NEWS_DELETE_FAIL";

export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const NEWS_LIST_FAIL = "NEWS_LIST_FAIL";

export const NEWS_BY_ID_SUCCESS = "NEWS_BY_ID_SUCCESS";
export const NEWS_BY_ID_FAIL = "NEWS_BY_ID_FAIL";

export const NEWS_MEDIA_SUCCESS = "NEWS_MEDIA_SUCCESS";
export const NEWS_MEDIA_FAIL = "NEWS_MEDIA_FAIL";

export const NEWS_MEDIA_DELETE_SUCCESS = "NEWS_MEDIA_DELETE_SUCCESS";
export const NEWS_MEDIA_DELETE_FAIL = "NEWS_MEDIA_DELETE_FAIL";

export const NEWS_PARAGRAPH_SUCCESS = "NEWS_PARAGRAPH_SUCCESS";
export const NEWS_PARAGRAPH_FAIL = "NEWS_PARAGRAPH_FAIL";

export const NEWS_PARAGRAPH_UPDATE_SUCCESS = "NEWS_PARAGRAPH_UPDATE_SUCCESS";
export const NEWS_PARAGRAPH_UPDATE_FAIL = "NEWS_PARAGRAPH_UPDATE_FAIL";

export const NEWS_PARAGRAPH_DELETE_SUCCESS = "NEWS_PARAGRAPH_DELETE_SUCCESS";
export const NEWS_PARAGRAPH_DELETE_FAIL = "NEWS_PARAGRAPH_DELETE_FAIL";

export const NEWS_PARAGRAPH_BY_ID_SUCCESS = "NEWS_PARAGRAPH_BY_ID_SUCCESS";
export const NEWS_PARAGRAPH_BY_ID_FAIL = "NEWS_PARAGRAPH_BY_ID_FAIL";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
