export const PROJECT_REQUEST = "PROJECT_REQUEST";
export const PROJECT_SUCCESS = "PROJECT_SUCCESS";
export const PROJECT_FAIL = "PROJECT_FAIL";

export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAIL = "PROJECT_LIST_FAIL";

export const PROJECT_BY_ID_SUCCESS = "PROJECT_BY_ID_SUCCESS";
export const PROJECT_BY_ID_FAIL = "PROJECT_BY_ID_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";