export const PROJECT_REQUEST = "PROJECT_REQUEST";

export const PROJECT_SUCCESS = "PROJECT_SUCCESS";
export const PROJECT_FAIL = "PROJECT_FAIL";

export const PROJECT_UPDATAE_SUCCESS = "PROJECT_UPDATE_SUCCESS";
export const PROJECT_UPDATE_FAIL = "PROJECT_UPDATE_FAIL";

export const PROJECT_DELETE_SUCCESS = "PROJECT_DELETE_SUCCESS";
export const PROJECT_DELETE_FAIL = "PROJECT_DELETE_FAIL";

export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAIL = "PROJECT_LIST_FAIL";

export const PROJECT_BY_ID_SUCCESS = "PROJECT_BY_ID_SUCCESS";
export const PROJECT_BY_ID_FAIL = "PROJECT_BY_ID_FAIL";

export const PROJECT_MEDIA_SUCCESS = "PROJECT_MEDIA_SUCCESS";
export const PROJECT_MEDIA_FAIL = "PROJECT_MEDIA_FAIL";

export const PROJECT_MEDIA_DELETE_SUCCESS = "PROJECT_MEDIA_DELETE_SUCCESS";
export const PROJECT_MEDIA_DELETE_FAIL = "PROJECT_MEDIA_DELETE_FAIL";

export const PROJECT_PARAGRAPH_SUCCESS = "PROJECT_PARAGRAPH_SUCCESS";
export const PROJECT_PARAGRAPH_FAIL = "PROJECT_PARAGRAPH_FAIL";

export const PROJECT_PARAGRAPH_UPDATE_SUCCESS = "PROJECT_PARAGRAPH_UPDATE_SUCCESS";
export const PROJECT_PARAGRAPH_UPDATE_FAIL = "PROJECT_PARAGRAPH_UPDATE_FAIL";

export const PROJECT_PARAGRAPH_DELETE_SUCCESS = "PROJECT_PARAGRAPH_DELETE_SUCCESS";
export const PROJECT_PARAGRAPH_DELETE_FAIL = "PROJECT_PARAGRAPH_DELETE_FAIL";

export const PROJECT_PARAGRAPH_BY_ID_SUCCESS = "PROJECT_PARAGRAPH_BY_ID_SUCCESS";
export const PROJECT_PARAGRAPH_BY_ID_FAIL = "PROJECT_PARAGRAPH_BY_ID_FAIL";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
