export const RESETPASSWORD_REQUEST = "RESETPASSWORD_REQUEST";

export const RESETPASSWORD_SUCCESS = "RESETPASSWORD_SUCCESS";
export const RESETPASSWORD_FAIL = "RESETPASSWORD_FAIL";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
