export const VOLUNTEER_REQUEST = "VOLUNTEER_REQUEST";

export const VOLUNTEER_SUCCESS = "VOLUNTEER_SUCCESS";
export const VOLUNTEER_FAIL = "VOLUNTEER_FAIL";

export const VOLUNTEER_UPDATAE_SUCCESS = "VOLUNTEER_UPDATE_SUCCESS";
export const VOLUNTEER_UPDATE_FAIL = "VOLUNTEER_UPDATE_FAIL";

export const VOLUNTEER_DELETE_SUCCESS = "VOLUNTEER_DELETE_SUCCESS";
export const VOLUNTEER_DELETE_FAIL = "VOLUNTEER_DELETE_FAIL";

export const VOLUNTEER_LIST_SUCCESS = "VOLUNTEER_LIST_SUCCESS";
export const VOLUNTEER_LIST_FAIL = "VOLUNTEER_LIST_FAIL";

export const VOLUNTEER_BY_ID_SUCCESS = "VOLUNTEER_BY_ID_SUCCESS";
export const VOLUNTEER_BY_ID_FAIL = "VOLUNTEER_BY_ID_FAIL";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
